### ISSUE TITLE
error Cannot read property 'allContentfulGallery' of undefined

### ISSUE THREAD

**Issue by omerkunul** [ryanwiemer/knw#1]
error Cannot read property 'allContentfulGallery' of undefined

  TypeError: Cannot read property 'allContentfulGallery' of undefined
  
  - gatsby-node.js:39 graphql.then.result
    /Users/dev/gatsby/gatsby/examples/knw/gatsby-node.js:39:18
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:606 Promise._settlePromiseCtx
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:606:10
  
  - async.js:138 Async._drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12
  
  - async.js:143 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
  

error UNHANDLED REJECTION

  TypeError: Cannot read property 'allContentfulGallery' of undefined
  
  - gatsby-node.js:39 graphql.then.result
    /Users/dev/gatsby/gatsby/examples/knw/gatsby-node.js:39:18
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:606 Promise._settlePromiseCtx
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:606:10
  
  - async.js:138 Async._drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12
  
  - async.js:143 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14

**Comment by ryanwiemer** [comment]
@omerkunul, 

The error your are receiving is due to missing the relevant Contentful Space ID and API Token which are purposefully not stored in the code base. This repository is not intended to serve as a template but you are welcome to look around at the code and learn from it. 

If you are just starting out with Gatsby I would recommend reading the official [tutorial](https://www.gatsbyjs.org/tutorial/) or grab a [Gatsby Starter](https://www.gatsbyjs.org/docs/gatsby-starters/). 

Best of luck to you!
